apiVersion: pg.percona.com/v1
kind: Pgtask
metadata:
  labels:
    pg-cluster: cluster3
    pgouser: admin
  name: cluster3-backrest-full-backup5
spec:
  name: cluster3-backrest-full-backup5
  parameters:
    backrest-command: backup
# backup type can be:
# Differential: Create a backup of everything since the last full backup was taken
# --type=diff
# Full: Back up the entire database
# --type=full
# Incremental: Back up everything since the last backup was taken, whether it was full, differential, or incremental
# --type=incr
# backup retention can be:
# --repo1-retention-full=2 how many full backups to retain
# --repo1-retention-diff=4 how many differential backups to retain
# --repo1-retention-archive=6 how many sets of WAL archives to retain alongside
# the full and differential backups that are retained
    backrest-opts: --type=full --repo1-retention-full=2
    backrest-s3-verify-tls: "false"
    # backrest-storage-type: ""
    job-name: cluster3-backrest-full-backup5
    pg-cluster: cluster3
  tasktype: backrest