apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  namespace: main-db
  name: pgconfig
spec:
  postgresVersion: "14"
  postgresql.conf:
    autovacuum_max_workers: '3'
    autovacuum_vacuum_cost_delay: '2'
    autovacuum_work_mem: '512MB'
    checkpoint_completion_target: '0.9'
    checkpoint_timeout: '15min'
    default_statistics_target: '200'
    enable_partitionwise_aggregate: 'on'
    enable_partitionwise_join: 'on'
    huge_pages: 'off'
    jit_inline_above_cost: '-1'
    log_autovacuum_min_duration: '0ms'
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: db: %d,user: %u,app: %a,client: %h '
    log_lock_waits: 'on'
    log_min_duration_statement: '1000'
    log_statement: 'none'
    log_temp_files: '0'
    maintenance_work_mem: '2GB'
    max_locks_per_transaction: '128'
    max_pred_locks_per_transaction: '128'
    max_prepared_transactions: '32'
    max_replication_slots: '20'
    max_wal_senders: '20'
    max_wal_size: '2GB'
    min_wal_size: '1GB'
    pg_stat_statements.track_utility: 'off'
    random_page_cost: '1.5'
    shared_preload_libraries: 'pg_stat_statements, auto_explain'
    superuser_reserved_connections: '8'
    track_activity_query_size: '4096'
    track_functions: 'pl'
    track_io_timing: 'on'
    wal_keep_size: '1536MB'
    work_mem: '10MB'
    max_connections: '5000'