apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-main-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      type: main
      app: pgbouncer
  template:
    metadata:
      labels:
        type: main
        app: pgbouncer
    spec:
      containers:
      - image: bitnami/pgbouncer
        name: pgbouncer
        ports:
        - containerPort: 6432
          hostPort: 9343 # forces it to only run once per node
        resources:
          requests:
            cpu: 400m # todo: not applied 700m
        envFrom:
          - configMapRef:
              name: pgbouncer-config
        env:
          - name: POSTGRESQL_HOST
            value: 10.2.0.1
          - name: POSTGRESQL_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom: { secretKeyRef: { name: stackgres-secrets, key: username } }
          - name: POSTGRESQL_PASSWORD
            valueFrom: { secretKeyRef: { name: stackgres-secrets, key: password } }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ram
                operator: NotIn
                values:
                - 8gb
              - key: dbsize
                operator: NotIn
                values:
                - "true"
              - key: nginx
                operator: In # Always in nginx now
                values:
                - "true"
                - "extra-large"
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-main-service
spec:
  ports:
  - port: 6432
    protocol: TCP
    targetPort: 6432
  selector:
    type: main
    app: pgbouncer