apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
data:
  PGBOUNCER_DATABASE: "*"
  PGBOUNCER_POOL_MODE: transaction
  # PGBOUNCER_QUERY_WAIT_TIMEOUT: 120
  PGBOUNCER_MAX_CLIENT_CONN: "50000"
  PGBOUNCER_DEFAULT_POOL_SIZE: "150"
  PGBOUNCER_SERVER_IDLE_TIMEOUT: "600"
  PGBOUNCER_AUTH_USER: postgres # See https://www.enterprisedb.com/postgres-tutorials/pgbouncer-authquery-and-authuser-pro-tips
  PGBOUNCER_AUTH_QUERY: SELECT usename, passwd FROM pg_shadow WHERE usename=$1
  PGBOUNCER_IGNORE_STARTUP_PARAMETERS: extra_float_digits statement_timeout
  # PGBOUNCER_IDLE_TRANSACTION_TIMEOUT: "480"