---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: ms0O4sY0Vix0Qp9m5E_51A
      keySecretRef:
        name: zero-ssl-eabsecret
        key: secret
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sponsor-cert
spec:
  dnsNames:
    - sponsor.ajay.app
    - api.sponsor.ajay.app
  secretName: sponsor-cert
  issuerRef:
    name: zerossl
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  dnsNames:
    - k8s.sponsor.ajay.app
  secretName: test-cert
  issuerRef:
    name: zerossl
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: graph-cert
  namespace: monitoring
spec:
  dnsNames:
    - graph.sponsor.ajay.app
  secretName: graph-cert
  issuerRef:
    name: zerossl
    kind: ClusterIssuer
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: longhorn-cert
#   namespace: longhorn-system
# spec:
#   dnsNames:
#     - longhorn.sponsor.ajay.app
#   secretName: longhorn-cert
#   issuerRef:
#     name: zerossl
#     kind: ClusterIssuer