repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  wait: true
  createNamespace: true
  cleanupOnFail: true

releases:
- name: prometheus-operator
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  disableValidation: true
  values:
    - prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 50Gi
  set:
    - name: grafana.image.tag
      value: "11.2.1"
    - name: grafana.persistence.enabled
      value: true
    - name: grafana.persistence.size
      value: 10Gi
    - name: grafana.podDisruptionBudget.minAvailable
      value: 0
    - name: grafana.podDisruptionBudget.maxUnavailable
      value: 0
    - name: grafana.deploymentStrategy.type
      value: Recreate
    - name: prometheus.prometheusSpec.resources.requests.cpu
      value: 500m
    - name: prometheus.prometheusSpec.retention
      value: "90d"
    - name: prometheus.prometheusSpec.scrapeInterval
      value: "30s"
    - name: prometheus.prometheusSpec.evaluationInterval
      value: "30s"
    - name: prometheus.prometheusSpec.resources.requests.memory
      value: 3500Mi