apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  name: poolconfig
  namespace: second-db
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: transaction
        max_client_conn: '20000'
        default_pool_size: '400'
        listen_backlog: '300'
        log_connections: '1'
        log_disconnections: '1'
        log_stats: '1'
        server_idle_timeout: '120'
        client_idle_timeout: '30'
        idle_transaction_timeout: '480'
        # query_wait_timeout: '300'
      # databases:
      #   demo:
      #     pool_size: 400
      #     dbname: 'demo'
      #     reserve_pool: 5
      #   postgres:
      #     pool_size: 10
      #     dbname: 'postgres'
      #     reserve_pool: 5
