apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- 03-SGInstanceProfile.yaml
- 04-SGPostgresConfig.yaml
- 05-SGPoolingConfig.yaml
- 06-SGDistributedLogs.yaml
- 07-SGObjectStorage.yaml