# NOTE: never worked, use https://www.percona.com/doc/kubernetes-operator-for-postgresql/standby.html instead
apiVersion: pg.percona.com/v1
kind: Pgtask
metadata:
  labels:
    pg-cluster: cluster1
    pgouser: postgres
  name: cluster3-backrest-restore
spec:
  name: cluster3-backrest-restore
  parameters:
    backrest-restore-from-cluster: cluster1
    # backrest-restore-opts: --type=time --target="2022-07-15 13:15:00"
    backrest-restore-opts: --pgbackrest-s3-verify-tls=false --no-repo-s3-verify-tls
    # backrest-storage-type: posix
    backrest-s3-verify-tls: "false"
    backrest-storage-type: s3
    # backrest-storage-type: local
  tasktype: restore