apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-server-deployment
spec:
  replicas: 28
  selector:
    matchLabels:
      app: sb-server
      method: post
  template:
    metadata:
      labels:
        app: sb-server
        method: post
    spec:
      containers:
      - image: ghcr.io/ajayyy/sb-server@sha256:5bd0ca8708e032fd4768bab5a9b1a8ebfcbaebdee622b566ea9386ffb67d3d70
        name: sb-server
        resources:
          requests:
            cpu: 800m
            memory: 2Gi
          limits:
            memory: 2Gi
        envFrom:
          - configMapRef:
              name: sb-server-config
        env:
          - name: postgres_user
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: username } }
          - name: postgres_password
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: password } }
          - name: postgresReadOnly_user
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: username } }
          - name: postgresReadOnly_password
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: password } }
          - name: globalSalt
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: globalSalt
                optional: false
          - name: discordReportChannelWebhookURL
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: discordReportChannelWebhookURL
                optional: false
          - name: discordFailedReportChannelWebhookURL
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: discordFailedReportChannelWebhookURL
                optional: false
          - name: discordFirstTimeSubmissionsWebhookURL
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: discordFirstTimeSubmissionsWebhookURL
                optional: false
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ram
                operator: NotIn
                values:
                - 8gb
              - key: dbsize
                operator: NotIn
                values:
                - "true"
              - key: nginx
                operator: NotIn
                values:
                - "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-server-read-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: sb-server
      method: get
  template:
    metadata:
      labels:
        app: sb-server
        method: get
    spec:
      containers:
      - image: ghcr.io/ajayyy/sb-server@sha256:5bd0ca8708e032fd4768bab5a9b1a8ebfcbaebdee622b566ea9386ffb67d3d70
        name: sb-server
        resources:
          requests:
            cpu: 800m
            memory: 1.5Gi
          limits:
            memory: 1.5Gi
        envFrom:
          - configMapRef:
              name: sb-server-config
        env:
          - name: postgres_user
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: username } }
          - name: postgres_password
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: password } }
          - name: postgresReadOnly_user
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: username } }
          - name: postgresReadOnly_password
            valueFrom: { secretKeyRef: { name: cluster3-postgres-secret, key: password } }
          - name: globalSalt
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: globalSalt
                optional: false
          - name: discordReportChannelWebhookURL
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: discordReportChannelWebhookURL
                optional: false
          - name: discordFailedReportChannelWebhookURL
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: discordFailedReportChannelWebhookURL
                optional: false
          - name: discordFirstTimeSubmissionsWebhookURL
            valueFrom:
              secretKeyRef:
                name: sb-server-secrets
                key: discordFirstTimeSubmissionsWebhookURL
                optional: false
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ram
                operator: NotIn
                values:
                - 8gb
              - key: dbsize
                operator: NotIn
                values:
                - "true"
              - key: nginx
                operator: NotIn
                values:
                - "true"
---
apiVersion: v1
kind: Service
metadata:
  name: sb-server-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sb-server
    method: post
---
apiVersion: v1
kind: Service
metadata:
  name: sb-server-read-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sb-server