apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-server-deployment
spec:
  replicas: 15
  selector:
    matchLabels:
      app: error-server
  template:
    metadata:
      labels:
        app: error-server
      name: error-server
    spec:
      containers:
      - image: ghcr.io/ajayyy/error-server:latest
        name: error-server
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ram
                operator: NotIn
                values:
                - 8gb
              - key: dbsize
                operator: NotIn
                values:
                - "true"
              - key: nginx
                operator: In
                values:
                - "true"
                - "extra-large"
---
apiVersion: v1
kind: Service
metadata:
  name: error-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: error-server