apiVersion: v1
kind: ConfigMap
metadata:
  name: keydb-config
data:
    # latency-monitor-threshold 200
  keydb-config: |
    maxmemory-policy allkeys-lru
    maxmemory 4500mb

    appendonly no
    save ""

    server-threads 4